##########################################################################################################
###      _            _                                                                             _  ###
###     | |          | |                                                                           | | ###
###   __| | ___   ___| | _____ _ __ ______ ___ ___  _ __ ___  _ __   ___  ___  ___  _   _ _ __ ___ | | ###
###  / _` |/ _ \ / __| |/ / _ \ '__|______/ __/ _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \| | | | '_ ` _ \| | ###
### | (_| | (_) | (__|   <  __/ |        | (_| (_) | | | | | | |_) | (_) \__ \  __/| |_| | | | | | | | ###
###  \__,_|\___/ \___|_|\_\___|_|         \___\___/|_| |_| |_| .__/ \___/|___/\___(_)__, |_| |_| |_|_| ###
###                                                          | |                     __/ |             ###
###                                                          |_|                    |___/              ###
###   nginx -> default image                                                                           ###
###   php-fpm-buster -> dockerfile                                                                     ###
###   @author antonio.rodrigo@digitalvirgo.com                                                         ###
##########################################################################################################

### In anfitrion machine ###
### To install docker services (into .docker directory):
# docker-compose-v1.exe up -d --force-recreate --build
# docker-compose up -d --force-recreate --build

### To entry in project container:
# docker exec -it xx_COMPOSE_PROJECT_NAME bash ### normal user
# docker exec -it -u root xx_COMPOSE_PROJECT_NAME bash ### root

######################## project compress ########################
### symfony
### ---> sh /scripts/scriptActionsParams.sh -p symfony -v
### angular
### ---> sh /scripts/scriptActionsParams.sh -p angular -v
########################  project compress ########################

### INIT docker-composer FILE ###
version: '3.9'

services:

  ### web Server projects ###
  ### NGINX
  nginx:
    container_name: ${PREFIX_PROJECT_NAME}_nginx_${NGINX_VER}
    image: nginx:${NGINX_VER}
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_S}:443
    environment:
      WWW_PATH_INT: ${WWW_PATH_INT}
    volumes:
      - ${WWW_PATH_EXT}:${WWW_PATH_INT}
      - ./configFiles/nginx-default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
      ### MEMORY VALORS
    mem_reservation: ${MEMORY_RESERVATION}
    mem_limit: ${MEMORY_LIMIT}

  ### PHP
  php:
    container_name: ${PREFIX_PROJECT_NAME}_php_fpm_${PHP_VER}
    build:
      # context: "Dockerfile-php-pdo_mysql-pdo_pgsql-pdo_sqlsrv" ### SqlServer
      # context: ".Dockerfile-php-pdo_mysql-pdo_pgsql" ### => RaspberryPi
      context: ./ ### dockerfiles dir
      dockerfile: Dockerfile-php-pdo_mysql-pdo_pgsql-pdo_sqlsrv ### SqlServer
      # context: "." ### Dockerfile
      args:
          PHP_VER: ${PHP_VER}
    environment:
      WWW_PATH_INT: ${WWW_PATH_INT}
    volumes:
      - ${WWW_PATH_EXT}:${WWW_PATH_INT}
      - ./configFiles/php-custom.ini:/etc/php/${WWW_PATH_INT}/fpm/conf.d/99-custom.ini
      - ./configFiles/php-custom.ini:/etc/php/${WWW_PATH_INT}/cli/conf.d/99-custom.ini
      - ./configFiles/php-fpm-pool.conf:/etc/php/${WWW_PATH_INT}/fpm/pool.d/zz-fpm-pool.conf
    user: ${PUID}:${PUID}
    working_dir: ${WWW_PATH_INT}
    restart: unless-stopped
    ### MEMORY VALORS
    mem_reservation: ${MEMORY_RESERVATION}
    mem_limit: ${MEMORY_LIMIT}
  ### web Server projects ###
  
  ### REDIS
  # redis:
  #   container_name: ${PREFIX_PROJECT_NAME}_redis_${REDIS_VER}
  #   image: redis:${REDIS_VER}
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - ./redis-data:/var/lib/redis
  #     - ./configFiles/redis.conf:/usr/local/etc/redis/redis.conf
  #   ports:
  #   - ${REDIS_PORT}:6379
  #   environment:
  #   - REDIS_REPLICATION_MODE=master
  #   restart: unless-stopped

networks:
  ${PREFIX_PROJECT_NAME}:
# #    ipam:
# #      config:
# #        - subnet: 172.16.238.0/24
# #          gateway: 172.16.238.1